name: Update - find - replace

on:
  workflow_dispatch: # Run manually
   

jobs:
  find-replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Find and Replace in HTML files
        run: |
          find . -type f -name "*.html" -exec sed -i 's|"./index_files/61bfb4a342750d81aff07ae0_SSSVV_Logo.png"|"/index_files/2026-SSVV-logo.png"|g' {} +
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update logo img links"
            git push
          fi
